GET https://translate.google.com/translate_a/single HTTP/1.1
Content-Type: application/json

{
  client: "gtx",
  sl: "pt",
  tl: "en",
  dt: "t",
  q: "Olá a todos"
}

###

POST https://translate.googleapis.com/translate_a/single HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  client: "gtx",
  sl: "pt",
  tl: "en",
  dt: "t",
  q: "Olá a todos"
}

###

POST https://translate.googleapis.com/translate_a/single HTTP/1.1
Content-Type: application/application/x-www-form-urlencoded


client=gtx&sl=pt&tl=en&dt=t&q=Olá a todos

###

POST https://fakerapi.it/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "_quantity": 1,
  "_locale": "pt_BR"
}