GET https://translate.google.com/translate_a/single HTTP/1.1
Content-Type: application/json

{
  client: "gtx",
  sl: "pt",
  tl: "en",
  dt: "t",
  q: "Olá a todos"
}

###

POST https://translate.googleapis.com/translate_a/single HTTP/1.1
content-type: application/x-www-form-urlencoded;charset=UTF-8

client=gtx&sl=pt&tl=en&dt=t&q=Olá a todos

###

GET https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&dt=%5B%22at%22%2C%22bd%22%2C%22ex%22%2C%22ld%22%2C%22md%22%2C%22qca%22%2C%22rw%22%2C%22rm%22%2C%22ss%22%2C%22t%22%5D&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=Ol%C3%A1+amigps&tk=882724.882724 HTTP/1.1
Accept: application/xml

###

GET https://fakerapi.it/api/v1/users HTTP/1.1
Content-Type: application/json

{
  "_quantity": 1,
  "_locale": "pt_BR"
}

###
POST https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=839064&rt=c HTTP/1.1
# POST https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-1989282645219493562&bl=boq_translate-webserver_20210127.10_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=839064&rt=c HTTP/1.1
accept: application/json
accept-language: en-US,en;q=0.9
# cache-control: no-cache
content-type: application/x-www-form-urlencoded;charset=UTF-8
# pragma: no-cache
# sec-fetch-dest: empty
# sec-fetch-mode: cors
# sec-fetch-site: same-origin
# x-same-domain: 1"
# # x-goog-batchexecute-bgr": "[\"FNLSecurityError: Blocked a frame with origin \\\"https://translate.google.com\\\" from accessing a cross-origin frame.\",null,null,5,null,null,null,0]",
# referrer: https://translate.google.com/
# referrerPolicy: origin
# method: POST
# mode: cors
# credentials: include

# f.req=%5B%5B%5B%22MkEWBc%22%2C%22%5B%5B%5C%22oicarlos%5C%22%2C%5C%22auto%5C%22%2C%5C%22en%5C%22%2Ctrue%5D%2C%5Bnull%5D%5D%22%2Cnull%2C%22generic%22%5D%5D%5D&
f.req=[[["MkEWBc","[[\"oi carlos\",\"auto\",\"en\",true],[null]]",null,"generic"]]]

###
# GET https://translate.googleapis.com/translate_a/single&amp;q=EgSKY8yMGM2-6oAGIhkA8aeDS8Qklz5ctP6cnz8AETE2KaL82YSfMgFy HTTP/1.1